server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://ijfhprcwofdocv:0ebe8f0495ece31f4be658c011fba4b12be2a5b7725053c7e003742b759a1f27@ec2-52-0-114-209.compute-1.amazonaws.com:5432/deiglij5748996
    username: ijfhprcwofdocv
    password: 0ebe8f0495ece31f4be658c011fba4b12be2a5b7725053c7e003742b759a1f27
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander